/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package analisis;

import javax.swing.JOptionPane;

/**
 *
 * @author Joel David
 */
public class HeapSort extends javax.swing.JFrame {
int Tam,persa,sum,i;
int Arreglo[];
int definir_tam=1;
int x;
String temporalposicion;
int posicion;

String temporalnuevovalor;
int nuevovalor;

String temporalnumero;
int buscarnumero;
    /**
     * Creates new form HeapSort
     */
    public HeapSort() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Tamaño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Numeros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Listas = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Acomodamiento = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo HeapSort");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Modificar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        Tamaño.setBackground(new java.awt.Color(255, 255, 255));
        Tamaño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamañoActionPerformed(evt);
            }
        });
        getContentPane().add(Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numeros a Procesar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, 30));

        Numeros.setBackground(new java.awt.Color(255, 255, 255));
        Numeros.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(Numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Método HeapSort");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Agregar Numero");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 30));

        Listas.setEditable(false);
        Listas.setBackground(new java.awt.Color(255, 255, 255));
        Listas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Listas.setToolTipText("");
        Listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListasActionPerformed(evt);
            }
        });
        getContentPane().add(Listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Ejecutar ordenamiento");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, 41));

        Acomodamiento.setEditable(false);
        Acomodamiento.setBackground(new java.awt.Color(255, 255, 255));
        Acomodamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Acomodamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcomodamientoActionPerformed(evt);
            }
        });
        getContentPane().add(Acomodamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 30));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setText("Limpiar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 70, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Regresar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BBBBBBBB.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-480, -270, 870, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (definir_tam==1){
                  Tam=Integer.parseInt(Tamaño.getText());
                  Arreglo = new int[Tam+1];
            
            }
        persa = Integer.parseInt(Numeros.getText());
        sum=sum+1;
        Arreglo[sum]=(persa);
        Numeros.setText("");
        String Resultado=Integer.toString(persa);
        Listas.setText(Listas.getText()+Resultado+"  ");
            definir_tam=2;
        if(sum==Tam){
          //  Indicador.setText("Llenado Completado");
            JOptionPane.showMessageDialog(this,"Llenado Copletado",
            "Información",JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Acomodamiento.setText("");
        for(i=Arreglo.length; i>1; i--){
  fnSortHeap(Arreglo, i - 1);
  }
        
        for(int x=1; x<Arreglo.length ; x++){
            String Completado=Integer.toString(Arreglo[x]);
            Acomodamiento.setText(Acomodamiento.getText()+Completado+"  ");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu_Principal regreso=new Menu_Principal();
        regreso.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
    Ventana_HeapSort reabrir= new Ventana_HeapSort();
    reabrir.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListasActionPerformed

    private void TamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamañoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        temporalnumero = JOptionPane.showInputDialog("Escriba el Numero a Modificar");
         int  buscarnumero=Integer.parseInt(temporalnumero);
      int contador=0;
      for( x=1;x<Arreglo.length;x++){
           if(Arreglo[x]==buscarnumero){
              contador=contador+1;
           }
           }
           if(contador==0){
               JOptionPane.showMessageDialog(this,"Numero No Encontrado",
                "Información",JOptionPane.INFORMATION_MESSAGE);  
           }
           if (contador==1){
               for( x=1;x<Arreglo.length;x++){
               if(Arreglo[x]==buscarnumero){
                JOptionPane.showMessageDialog(this,"Valor Encontrado",
               "Información",JOptionPane.INFORMATION_MESSAGE);
              
                  temporalnuevovalor = JOptionPane.showInputDialog("Escriba El Nuevo VALOR");
                  nuevovalor=Integer.parseInt(temporalnuevovalor);
                  Arreglo[x]=nuevovalor;
                
                   Listas.setText("");
                   for(int n=1; n<Arreglo.length ; n++){
                   String Modificacion=Integer.toString(Arreglo[n]);
                   Listas.setText(Listas.getText()+Modificacion+"  ");
                   
           }
           }
               
              
           }
           }
              
           if (contador>=2){
               int contador2=0;
               JOptionPane.showMessageDialog(this,"Valor Encontrado "+ contador+" veces",
                "Información",JOptionPane.INFORMATION_MESSAGE);
                  temporalposicion = JOptionPane.showInputDialog("Posicion del que Desea Modificar:");
                  posicion=Integer.parseInt(temporalposicion);
                  
          
              if ((posicion>0)&&(posicion<=contador)){
                   for( x=1;x<Arreglo.length;x++){  
                    if(Arreglo[x]==buscarnumero){
                       contador2=contador2+1;
                        if(contador2==posicion){
                  temporalnuevovalor = JOptionPane.showInputDialog("Escriba El Nuevo VALOR");
                  nuevovalor=Integer.parseInt(temporalnuevovalor);
                  Arreglo[x]=nuevovalor;
                
                   Listas.setText("");
                   for(int n=1; n<Arreglo.length ; n++){
                   String Modificacion=Integer.toString(Arreglo[n]);
                   Listas.setText(Listas.getText()+Modificacion+"  ");
                   
           }
                        }
           }
           }
           }else{
                   JOptionPane.showMessageDialog(this,"Posicion Invalida "+" Rango de 1 a "+ contador,
                "Información",JOptionPane.INFORMATION_MESSAGE);
              }
                  
              }
                  
               
                 
              
               
          
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AcomodamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcomodamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcomodamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_HeapSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_HeapSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_HeapSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_HeapSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_HeapSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Acomodamiento;
    private javax.swing.JTextField Listas;
    private javax.swing.JTextField Numeros;
    private javax.swing.JTextField Tamaño;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
	  public static void fnSortHeap(int array[], int arr_ubound){
	  int i, o;
	  int lChild, rChild, mChild, root, temp;
	  root = (arr_ubound-1)/2;

	  for(o = root; o >= 0; o--){
	  for(i=root;i>=0;i--){
	  lChild = (2*i)+1;
	  rChild = (2*i)+2;
	  if((lChild <= arr_ubound) && (rChild <= arr_ubound)){
	  if(array[rChild] >= array[lChild])
	  mChild = rChild;
	  else
	  mChild = lChild;
	  }
	  else{
	  if(rChild > arr_ubound)
	  mChild = lChild;
	  else
	  mChild = rChild;
	  }

	  if(array[i] < array[mChild]){
	  temp = array[i];
	  array[i] = array[mChild];
	  array[mChild] = temp;
	  }
	  }
	  }
	  temp = array[0];
	  array[0] = array[arr_ubound];
	  array[arr_ubound] = temp;
	  return;
	  }
	}
