/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package analisis;

import javax.swing.JOptionPane;

/**
 *
 * @author Joel David
 */
public class Ventana_QuickSort extends javax.swing.JFrame {
int Tam,sum,persa;
int Arreglo[];
int definir_tam=1;



    /**
     * Creates new form Ventana_QuickSort
     */
    public Ventana_QuickSort() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tamaño = new javax.swing.JTextField();
        Numeros = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Listas = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Acomodamiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo MergeSort");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tamaño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 20));

        Numeros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(Numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Agregar Numero");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 30));

        Listas.setEditable(false);
        Listas.setBackground(new java.awt.Color(255, 255, 255));
        Listas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Listas.setToolTipText("");
        getContentPane().add(Listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Ordenar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 41));

        Acomodamiento.setEditable(false);
        Acomodamiento.setBackground(new java.awt.Color(255, 255, 255));
        Acomodamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(Acomodamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Método QuickSort");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Limpiar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Regresar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("desordenado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Ordenado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Numeros a Procesar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 30));

        getAccessibleContext().setAccessibleName("Ordernar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (definir_tam==1){
                  Tam=Integer.parseInt(Tamaño.getText());
                  Arreglo = new int[Tam+1];
            
            }
        
        persa = Integer.parseInt(Numeros.getText());
        sum=sum+1;
        Arreglo[sum]=(persa);
        Numeros.setText("");
        String Resultado=Integer.toString(persa);
        Listas.setText(Listas.getText()+Resultado+"  ");
        definir_tam=2;
        if(sum==Tam){
          //  Indicador.setText("Llenado Completado");
            JOptionPane.showMessageDialog(this,"Llenado Copletado",
                "Información",JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         ordenarQuicksort(Arreglo,0,Arreglo.length-1);
         
        for(int x=1;x<Arreglo.length ; x++){
            String Completado=Integer.toString(Arreglo[x]);
            Acomodamiento.setText(Acomodamiento.getText()+Completado+"  ");

}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu_Principal regreso=new Menu_Principal();
        regreso.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            this.setVisible(false);
    Ventana_QuickSort reabrir= new Ventana_QuickSort();
    reabrir.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_QuickSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_QuickSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_QuickSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_QuickSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_QuickSort().setVisible(true);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Acomodamiento;
    private javax.swing.JTextField Listas;
    private javax.swing.JTextField Numeros;
    private javax.swing.JTextField Tamaño;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
public static void ordenarQuicksort(int[] vector, int primero, int ultimo){
			int i=primero, j=ultimo;
			int pivote=vector[(primero + ultimo) / 2];
			int auxiliar;
		do{
			while(vector[i]<pivote) i++; 
			while(vector[j]>pivote) j--;
			if (i<=j){
				auxiliar=vector[j];
				vector[j]=vector[i];
				vector[i]=auxiliar;
				i++;
				j--;
			}
		} while (i<=j);
			if(primero<j) ordenarQuicksort(vector,primero, j);
			if(ultimo>i) ordenarQuicksort(vector,i, ultimo);
		}
	}



